os:
  editPreset: "vim"
  editInTerminal: true

customCommands:
  - key: "G"
    command: "gh pr view -w {{.SelectedLocalBranch.Name}}"
    context: "localBranches"
    description: "Go to PR in github"
    stream: true

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
